### ISSUE TITLE
cannot save settings geographich extent/subset 

### ISSUE THREAD

**Issue by ctottrup** [DHI-GRAS/qgis-processing-workflow#1]
unable to save the settings for geographich extent/subset when using gdal translate in preparation of a new workflow

**Comment by wuwwen** [comment]
That's because when saving workflow, it will call update step method. But it hasn't store the parameter of  ParameterExtent into workflow steps. This has been fixed. Please get the latest code to test it.

**Comment by j08lue** [comment]
I take this is fixed.
