### ISSUE TITLE
Port to QGIS 3

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/qgis-processing-workflow#14]
This plugin needs to be ported to QGIS 3. Can we map out what steps are needed for this? Obviously

- [ ] Port Python 2 to Python 3 code (trivial)
- [ ] Port Qt4 to Qt5 (not so simple)
- [ ] Port PyQGIS (???)

Here is the official guide https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3

And maybe the `qgis2to3` migration tool can lift most of the first two points and also help with the third https://github.com/opengisch/qgis2to3?

**Comment by radosuav** [comment]
This is now done and first version released: https://github.com/DHI-GRAS/qgis-processing-workflow/releases/tag/2.0.0
