### ISSUE TITLE
Uncaught IOError: [Errno 9] Bad file descriptor


### ISSUE THREAD

**Issue by Sirbay** [DHI-GRAS/qgis-processing-workflow#16]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/hp/.qgis2/python/plugins\cadtools\tools\modifycirculararctool.py", line 103, in deactivate
    print "***************** deactivate modifycirculararctool"
IOError: [Errno 9] Bad file descriptor

```
processing_workflow 1.3.2, QGIS 2.18.28 on Windows 10

**Comment by radosuav** [comment]
This is a problem caused by print statement in the CAD Tools plugin. You should open an issue on that plugin's repository. In the meantime, you can open the QGIS Python console before you run this algorithm to avoid the IOError and print the message to the console..
