### ISSUE TITLE
error message on close after editing workflow in QGIS version 2.12 and above

### ISSUE THREAD

**Issue by corinnar** [DHI-GRAS/qgis-processing-workflow#3]

**Comment by j08lue** [comment]
More details from Corinna (thanks!):

On recent versions of QGIS there seems to be a problem on exit of the workflow tool. In versrion 2.8.8 (the long term release) there is no problem but from QGIS 2.12 and above I get an error message upon close after editing a workflow. It still runs and saves correctly but upon hitting close I get the following error message. I don’t think it is my computer as it occurs on more than one computer. 

![issue2](https://cloud.githubusercontent.com/assets/3404817/15174291/2700eb3c-1761-11e6-9401-9d82560102da.jpg)

**Comment by radosuav** [comment]
@corinnar please try the latest version of the plugin (1.2) on QGIS 2.14 (the new long term release). The new version also includes new features, including the ability to add instruction-only steps. See https://github.com/DHI-GRAS/processing_workflow/blob/GW-A_dev/README.md for details.

**Comment by j08lue** [comment]
Since we did not hear anything more of this issue, I will close it.
