### ISSUE TITLE
Preserve HTML styling of text in left-hand panel

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/qgis-processing-workflow#5]
From user C. (thanks for reporting this!):

One thing I have been doing has been styling the text in the left hand panel. I.e. rather than plain text I have been pasting in some html text. This makes the workflow look very professional when run. The only thing is that as soon as I add a new step to the workflow the html styling disappears and I have to paste it in again for every step. Not a problem but if in your development you can get it to maintain the html styling that would be good. 

Example screen grab of one of our workflows below:

![issue4](https://cloud.githubusercontent.com/assets/3404817/15174345/75be5c8c-1761-11e6-832b-aec77256ebe6.jpg)

**Comment by radosuav** [comment]
This should be addressed in the latest plugin release with the use of Markdown and CSS to style the instructions.
