### ISSUE TITLE
Wrong processing workflows path

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/qgis-processing-workflow#7]
is `.qgis2/python/plugins\processing_workflow\workflows`

should be `.qgis2\processing\workflows`

![image](https://cloud.githubusercontent.com/assets/3404817/16368630/a2aef2d0-3c30-11e6-868b-5c563b338d9b.png)

**Comment by j08lue** [comment]
Fixed. However, if the path is already set (in Windows registry) from an earlier installation, it only gets updated if the old target directory does not exist anymore (see https://github.com/DHI-GRAS/processing_workflow/commit/28378d52c944ecc66b7cf4ca3f6adf7e01b9a31d).

**Comment by radosuav** [comment]
In case of WOIS installation maybe it could be handled in activateProcessingProviders function (https://github.com/TIGER-NET/WOIS_Installer/blob/master/woisInstaller.py#L584).

In case of standalone plugin installation it's up to the user anyway to decide where they want to keep the workflows.

**Comment by j08lue** [comment]
Ah, so was it wrong to change it here https://github.com/DHI-GRAS/processing_workflow/commit/9fe562c928d4c2b91345a16eab4c5713292ebdd8 ?

**Comment by radosuav** [comment]
It was good :) The default path should be .qgis2\processing\workflows. 

I just meant it in relation to your previous comment about path only being updated if the old directory does not exist anymore. 

But now that I think about it, WOIS installer deletes the old processing_workflow plugin so .qgis2/python/plugins\processing_workflow\workflows won't exist and the proper workflows' path should be set without any more modifications.

**Comment by j08lue** [comment]
:-) yay
